# Change these first
owner: revolt-chat # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: API
    url: https://api.revolt.chat
  - name: CDN
    url: https://autumn.revolt.chat?t=2
  - name: Voice
    url: https://vortex.revolt.chat
  - name: Proxy Service
    url: https://jan.revolt.chat
  - name: Client
    url: https://app.revolt.chat
  - name: Static Resources
    url: https://static.revolt.chat
    expectedStatusCodes:
      - 200
      - 404
  - name: Mail
    check: "tcp-ping"
    url: $MAIL_SERVER
    port: 25

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.revolt.chat
  # baseUrl: /your-repo-name
  logoUrl: https://app.revolt.chat/assets/logo_round.png
  name: Revolt
  introTitle: "Revolt Service Status"
  introMessage: "Revolt is a user-first chat platform built with modern web technologies."
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://revolt.chat

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
