owner: revolt-chat
repo: status

sites:
  - name: Web Frontend (Revite)
    url: https://app.revolt.chat
  - name: API (Delta)
    url: https://api.revolt.chat
  - name: User Content (Autumn)
    url: https://cdn.revoltusercontent.com
  - name: Proxy Service (January)
    url: https://jan.revolt.chat
  - name: Voice (Vortex)
    url: https://vortex.revolt.chat
  - name: Static Resources
    url: https://static.revolt.chat
    expectedStatusCodes:
      - 200
      - 404
  - name: Mail
    check: "tcp-ping"
    url: $MAIL_SERVER
    port: 25

status-website:
  cname: status.revolt.chat
  logoUrl: https://revolt.chat/favicon.svg
  faviconSvg: https://revolt.chat/favicon.svg
  themeUrl: https://status.revolt.chat/theme.css
  name: Revolt Status
  introTitle: "Revolt Service Status"
  introMessage: "Revolt is the chat app that's truly built with you in mind. This page documents current and historical service status, as well as upcoming forecasted downtime."
  navbar:
    - title: Website
      href: https://revolt.chat
    - title: Support
      href: https://support.revolt.chat
